backend:
  name: git-gateway
  branch: main # Make sure this matches the branch you are working on

media_library:
  name: uploadcare
  config:
    publicKey: demo

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }
