backend:
  name: git-gateway
  branch: main # Change this to your GitHub branch if different

media_library:
  name: uploadcare
  config:
    publicKey: demo

collections:
  - name: "mountains"
    label: "Mountains"
    folder: "content/mountains"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "markdown" }
