backend:
  name: git-gateway
  branch: main # Make sure this matches the default branch on your GitHub repository

media_library:
  name: uploadcare
  config:
    publicKey: demo

collections:
  - name: "blog" # This matches the 'blog' folder inside the 'content' folder
    label: "Blog Posts"
    folder: "content/blog" # This should point to the blog folder you created
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # This will auto-generate slugs for your posts based on the date
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
